##
##	Makefile for "ifeq()"  : funfun.yoo@gmail.com
##

PLATFORM =
CC = $(PLATFORM)gcc

CONFIG_LIB = shared

ifeq ($(CONFIG_LIB),static)
target : clean
	@echo "CONFIG_LIB: $(CONFIG_LIB)"
	$(MAKE) -C /home/pi/KDT/howto_lib_make_make -f Makefile.staticlib CC=$(CC)

else
target : clean
	@echo "CONFIG_LIB: $(CONFIG_LIB)" 
	$(MAKE) -C /home/pi/KDT/howto_lib_make -f Makefile.sharedlib CC=$(CC)
endif

clean :
	rm -f *.a *.so *.o mymain

